### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by NineBitsLTD** [cloudconvert/cloudconvert-node#40] opened 2019-09-16 16:55 UTC
include requires: fs, net with version to package.json. I am failing to install a module:
ERROR in ./node_modules/cloudconvert/lib/process.js
Module not found: Error: Can't resolve 'fs' in '/Users/air/Desktop/Projects/general/noplag-2018/source/node_modules/cloudconvert/lib'
 @ ./node_modules/cloudconvert/lib/process.js 5:9-22
 @ ./node_modules/cloudconvert/lib/api.js
In this case, the fs 0.0.1-security is installed.

**Comment by josiasmontag** [comment] 2020-01-08 16:08
I am closing this because the issue is related to the old v1 SDK. If you still have this problem with v2, feel free to open a new issue.

**Closed by josiasmontag** 2020-01-08 16:08 UTC
