### ISSUE TITLE
trying to convert and upload pdf on S3 with nodejs

### ISSUE THREAD

**Issue by mustafashaikh4714** [cloudconvert/cloudconvert-node#31] opened 2019-07-02 12:01 UTC
I have followed the guide as described at README.MD and it completes without errors but stills not getting the results.

i also tried posting the queries at stackoverflow.com 
https://stackoverflow.com/questions/56835950/trying-to-convert-docx-into-pdf-on-s3-using-cloudconvert-api-in-nodejs

**Comment by josiasmontag** [comment] 2020-01-08 16:08
I am closing this because the issue is related to the old v1 SDK. If you still have this problem with v2, feel free to open a new issue.

**Closed by josiasmontag** 2020-01-08 16:08 UTC
