### ISSUE TITLE
ApiError should include full body of response

### ISSUE THREAD

**Issue by orfin** [cloudconvert/cloudconvert-node#20] opened 2017-12-04 15:40 UTC
Hi!
We're extensively using CloudConvert for converting PDF files.

We're getting bunch of "Copying of text from this document is not allowed." errors when calling cloudconvert.get(URL TO PROCESS).

It's fine but it'd be superb useful if the whole response body be included in the Error object.

Just like adding this line: https://github.com/cloudconvert/cloudconvert-node/blob/master/lib/api.js#L42 :
```
apierror.body = body;
```

That way we will be able to get full status of failed conversion and for example use it in our logs.

Thanks!

**Comment by josiasmontag** [comment] 2020-01-08 16:08
I am closing this because the issue is related to the old v1 SDK. If you still have this problem with v2, feel free to open a new issue.

**Closed by josiasmontag** 2020-01-08 16:08 UTC
